#服务启动端口
server :  
  port :  8080
  context-path : /oloDingDing
#数据库配置
spring:
    datasource:
        #url: jdbc:oracle:thin:@192.168.2.38:1521:ecology 
        url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST =192.168.2.160)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = ecology)))
        #jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false&verifyServerCertificate=false
        username: ecology
        password: ecology
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        #com.mysql.jdbc.Driver
    redis:
      host: 127.0.0.1
      #redis密码，没有密码的可以用～表示
      password: ~
      port: 6379
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    http:
      multipart :
         enabled : false
    quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            useProperties: false
            dataSource: myDs
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            myDs:
              driver: oracle.jdbc.driver.OracleDriver
              URL: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST =192.168.2.160)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = ecology)))
              user: ecology
              password: ecology
              maxConnections : 30
              validationQuery : select 1 from dual

    jdbc-store-type: jdbc
# Mybatis mapper 映射路径配置
mybatis:
  type-aliases-package: com.olo.ding.mapper
  mapper-locations: classpath*:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
    
# 日志输出
logging: 
    file: D:/boot.log
    level: 
         com:
            olo:
              ding:
                mapper: DEBUG
        #com.ibatis:DEBUG
        #root:DEBUG,INFO,ERROR
task:
    cron:0 0/5 * * * ?
    


       
    
